[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_TCR2_ADDRESSES='{"42":"0x6445DeDf215f52f8002F1313F4F66e6Cca8972e6"}'
  REACT_APP_TCRVIEW_ADDRESSES='{"42":"0x774cda12c61f519bb0e8178304e72105269898b8"}'
