[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_DEFAULT_TCR_ADDRESSES='{"42":"0x18CFC49b76635A068C9f4530EfB852973f06Cb29"}'
  REACT_APP_DEFAULT_ARBITRATOR='{"42":"0x60b2abfdfad9c0873242f59f2a8c32a3cc682f80", "1": "0x988b3a538b618c7a603e1c11ab82cd16dbe28069"}'
  REACT_APP_GTCRVIEW_ADDRESSES='{"42":"0xd28f9f565f24ce5d9a3df63db186fb774f66468c"}'
  REACT_APP_METAMASK_SITE_URL='https://metamask.io'
  REACT_APP_TRUST_SITE_URL='https://trustwallet.com/'
  REACT_APP_WALLETCONNECT_BRIDGE_URL='https://bridge.walletconnect.org'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
