[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_DEFAULT_TCR_ADDRESSES='{"42":"0xBcb2F451c8462AeE3A58A1D6A5cffd262331d6B1"}'
  REACT_APP_GTCRVIEW_ADDRESSES='{"42":"0x13ad3561b4d0105ffe03d2a31bc462544eca54b4"}'
