[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_DEFAULT_TCR_ADDRESSES='{"42":"0x386202C4Ff539944B6DB5D396326B35d1AbD6E17"}'
  REACT_APP_DEFAULT_ARBITRATOR='{"42":"0x60b2abfdfad9c0873242f59f2a8c32a3cc682f80", "1": "0x988b3a538b618c7a603e1c11ab82cd16dbe28069"}'
  REACT_APP_DEFAULT_GOVERNOR='{"42":"0xdC8C1a8CB38F27C188a43CE0eBBC8e42e393D0d3", "1": "0x988b3a538b618c7a603e1c11ab82cd16dbe28069"}'
  REACT_APP_DEFAULT_EVIDENCE_DISPLAY_URI='/ipfs/QmayLFwzmjhduKxWTze1T7zi9Sx7scTEGQC5t8Sxi1L7so/index.html'
  REACT_APP_GTCRVIEW_ADDRESSES='{"42":"0xe53bf683bbb32940a33fac18c88ca6bc0950bf18"}'
  REACT_APP_BATCH_WITHDRAW_ADDRESSES='{"42":"0xA32942798112e561d4d3ffc62c552bb0E9651b66"}'
  REACT_APP_METAMASK_SITE_URL='https://metamask.io'
  REACT_APP_TRUST_SITE_URL='https://trustwallet.com/'
  REACT_APP_WALLETCONNECT_BRIDGE_URL='https://bridge.walletconnect.org'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
