[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_DEFAULT_TCR_ADDRESSES='{"42":"0x60CcCebb1bD7d87b0bc9FcE474f41e755A8e597a"}'
  REACT_APP_GTCRVIEW_ADDRESSES='{"42":"0x0030dbf8f20a11a7080d7bf26eb152f10f070639"}'
  REACT_APP_METAMASK_SITE_URL='https://metamask.io'
  REACT_APP_TRUST_SITE_URL='https://trustwallet.com/'
  REACT_APP_WALLETCONNECT_BRIDGE_URL='https://bridge.walletconnect.org'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
