[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_TCR2_ADDRESSES='{"42":"0x3B44672A1aB6942fC1B4DB46F170EFF402BAa836"}'
  REACT_APP_TCRVIEW_ADDRESSES='{"42":"0x774cda12c61f519bb0e8178304e72105269898b8"}'
