[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_IPFS_GATEWAY="https://ipfs.kleros.io"
  REACT_APP_DEFAULT_NETWORK="42"
  REACT_APP_DEFAULT_TCR_ADDRESSES='{"42":"0x0B0242727E939F0aEf432efE578c2f95261B1090"}'
  REACT_APP_GTCRVIEW_ADDRESSES='{"42":"0xdef5891c3020c1008d31779011f8fd60a4396ac2"}'
  REACT_APP_METAMASK_SITE_URL='https://metamask.io'
  REACT_APP_TRUST_SITE_URL='https://trustwallet.com/'
  REACT_APP_WALLETCONNECT_BRIDGE_URL='https://bridge.walletconnect.org'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
